### ISSUE TITLE
Homebridge won't launch: 

### ISSUE THREAD

**Issue by charles-philippe** [ExPHAT/homebridge-hunterdouglas#3]
`ECONNREFUSED: connect ECONNREFUSED 192.168.1.205:522`

Error on homebridge startup.... checked and double checked the ip.

Should there not be a password to use?

Thanks for any help!

**Comment by exPHAT** [comment]
@charles-philippe  You have Hunter Douglas platinum blinds? Not powerview?

**Comment by charles-philippe** [comment]
I have PowerView…

**Comment by charles-philippe** [comment]
Is that why it's not working? I need Hunter Doublas Platnum Blinds? Do you know of a PowerView Homebridge Plug-in?  Hope this can help others with my setup...

**Comment by exPHAT** [comment]
@charles-philippe Yes, powerview is the newer generation of the platinum shades.

I haven't had a chance to add support for the Powerview yet. Hopefully coming at some point in the future.

**Comment by webpablo** [comment]
Consider this a +1 for Powerview blind support. =D

**Comment by martijnmnnk** [comment]
I just learned that there now is a Powerview Homebridge plugin available, but haven't tested it yet. https://github.com/GvnCampbell/homebridge-powerview

**Comment by GvnCampbell** [comment]
That is a plugin I've been working on. It's been working well for my roller blinds for a number of months now. I'm working with another guy that has the tilt shades to try get it working with the tilt as well but it's a little difficult since I don't have them. 

Give it a shot and if you have problems let me know on the github repo.

**Comment by davidvanvo** [comment]
@GvnCampbell just installed this. appears to be working thus far. thanks!
